version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tennyros"
    labels:
      - "dependencies"
    commit-message:
      prefix: "[dependabot]"
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "github-actions"
    commit-message:
      prefix: "[actions]"
    open-pull-requests-limit: 0