version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tennyros"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"