version: '3.8'
services:
  spring-boot-jooq-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-users_db}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - "5433:5432"