server:
  port: 8181

spring:
  datasource:
    driverClassName: org.postgresql.Driver
  jooq:
    sql-dialect: postgres
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml